### ISSUE TITLE
Add features

### ISSUE THREAD

**Issue by HalfSealHalfCat** [MechHedgehog/infa_2020_yaskovets#2]
[In task 3](https://github.com/MechHedgehog/infa_2020_yaskovets/blob/master/Lab3/3.py)

1. Vary transparency for objects.
2. Create rays for the sun.
3. Provide colour choice for trees, mushrooms and sky.
4. Add some clouds and aminate some part of your picture.

**Comment by MechHedgehog** [comment]
1) Brand new sun with rays
2) New colors (I'M NOT A DESIGNER, I DO EVERYTHING, THAT I CAN)
3) New item - nut
4) Clouds with transparency and animation
