### ISSUE TITLE
Balls Lab

### ISSUE THREAD

**Issue by HalfSealHalfCat** [MechHedgehog/infa_2020_yaskovets#3]
In [task](https://github.com/MechHedgehog/infa_2020_yaskovets/tree/master/Balls%20Lab):

1. Reduce code duplicates as much as possible.
2. Provide more reasonable behaviour on keyboard events.
3. Check spacings.

**Comment by MechHedgehog** [comment]
1) Done.
2) Added play with your friend mode.
3) Checked.
4) P.S. Added forgotten picture of a star.
